### ISSUE TITLE
login not working

### ISSUE THREAD

**Issue by CardealRusso** [bakape/meguca#1080]
not working at all

**Comment by bakape** [comment]
What URL are you performing the login from?

**Comment by bno1** [comment]
I had the same problem when accessing the site from `http://localhost:8000`. The problem is that cookies are set for the root url (`127.0.0.1` by default). If you're accessing the site via another url login doesn't work. Either use `http://127.0.0.1:8000/` or change `RootURL` in `config/config.go` to whatever you want to use.
