### ISSUE TITLE
Save user settings by password instead of JSON file

### ISSUE THREAD

**Issue by underr** [bakape/meguca#171]
![example](http://a.pomf.se/hwrcyp.png)

Image is from DuckDuckGo settings.
As JSON don't work on Firefox, this could be a good idea.
Please close this issue if you don't think so, though.

**Comment by bakape** [comment]
Then I would have to store it server-side, which I really don't want to do for client-side options. The issue is that FF fails on https://github.com/bakape/meguca/blob/master/alpha/options/index.js#L187-L196 and I can't be assed to fix everything FF breaks in regression. If you have a solution to getting the above method working, feel free to PR.
