### ISSUE TITLE
More functional post hiding/Filter

### ISSUE THREAD

**Issue by Bozunee** [bakape/meguca#337]
Only option is hiding a single post and only permanently- something which also might need to get fixed.

Additions of smart filters for image hashes, filenames, hostnames, tripcodes, keywords, and the like are pretty standard for a chan.

**Comment by bakape** [comment]
Sadly, due to the realtime nature of posting and the fact that text and images can be added at any point in time, most that can be done is filters on post allocation (names and tripcodes). All others would have posts randomly disappearing, as soon as they type in a filtered keyword. 

>hostnames

What exactly do you mean? 

Otherwise, adding to the v2 milestone.

**Comment by Bozunee** [comment]
Meant to put postname on that one.
With the others put onto a filter I don't really see much of an issue of the post disappearing, or even turning into a stub if the keyword or image hash criteria gets fulfilled.
It's a client feature that would only affect the user personalizing their filter, so having half-written posts disappear due to hitting a flagged word or image would be the same as a post hidden all together outside of the realtime posting.

**Comment by bakape** [comment]
Fair point.

**Comment by bakape** [comment]
Superseded byt #777
