### ISSUE TITLE
can we get an auto install script like MegucaV1 had?

### ISSUE THREAD

**Issue by NIXOYE** [bakape/meguca#408]
it'd be really nice of you

**Comment by bakape** [comment]
We depend on system components much more strongly than v1,  so it would be
very difficult to properly write a script to work across multiple
distributions or even different versions of the same distribution. Best
thing to do would probably be to write a Docker container,  but I am
unfamiliar with Docker and it is quite a heavy subject to learn. If you can
find someone who can write the script,  it can be added to meguca.
Otherwise I don't see this happening any time soon.

**Comment by NIXOYE** [comment]
Ok, could the install instructions be simplified a bit then?

**Comment by Lightsockie** [comment]
I'll take a back rub while you're at it, Bakape. Also feelin' a bit peckish. Mind grabbin' me a bite?

**Comment by bakape** [comment]
>Ok, could the install instructions be simplified a bit then?

What is unclear, specifically?

**Comment by bakape** [comment]
I looked into Docker, and it does not provide the one click install you want. Generally it is a bad idea to enable people who don't have enough understanding to follow build instructions to mess with servers. 

If you have any specific questions about the installation procedures, I'll be glad to answer. Otherwise you could consider some alternative PHP image board software on a CPanel webhost.

**Comment by NIXOYE** [comment]
having the commands that install the dependencies and meguca itself in order would probably be enough. I remember before there were suggestions like making a new user specifically for meguca. Tips like that would also be nice for the front page

**Comment by bakape** [comment]
Those differ from system to system and even vary between different
distribution versions. You ultimately have to know or research what applies
to your case.

Those are only common deployment and security practices. Nothing that is
not well known or readily available elsewhere - nothing that should be in
the readme. A certain level of knowledge or research is generally expected,
when deploying a server in general.

**Comment by NIXOYE** [comment]
Having a numbered list with the commands written out for a debian server
would make it extremely simple for anyone on any linux server to then
translate the steps for themselves for whatever distribution their server
runs.

Sorry for being a bother, i just think it makes sense to have simple
instructions for installing and updating an instance.
