### ISSUE TITLE
Does the C++ library build on OS X?

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#767]
Having a problem [here](https://github.com/NixOS/nixpkgs/pull/41823).
Have you tested any emscripten stuff on a Mac? Think it might be a Nix-specific issue?
It seems to not want to build libcxxabi.

```
make[2]: Leaving directory '/private/tmp/nix-build-meguca-unstable-2018-07-01.drv-0/go/src/github.com/bakape/meguca/client_cpp/src'
emcc src/*.bc src/page/*.bc src/posts/*.bc src/options/*.bc src/connection/*.bc brunhild/*.bc -o linked.bc -std=c++1z --bind -O3 -g0 -I/private/tmp/nix-build-meguca-unstable-2018-07-01.drv-0/go/src/github.com/bakape/meguca/client_cpp/json/include --llvm-lto 3 -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY=67108864 -s ALLOW_MEMORY_GROWTH=1 -Wno-almost-asm -s NO_FILESYSTEM=1
emcc linked.bc -o main.js --separate-asm -Wno-separate-asm -std=c++1z --bind -O3 -g0 -I/private/tmp/nix-build-meguca-unstable-2018-07-01.drv-0/go/src/github.com/bakape/meguca/client_cpp/json/include --llvm-lto 3 -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY=67108864 -s ALLOW_MEMORY_GROWTH=1 -Wno-almost-asm -s NO_FILESYSTEM=1
INFO:root:generating system library: libcxx_noexcept.a... (this will be cached in "/private/tmp/nix-build-meguca-unstable-2018-07-01.drv-0/.emscripten_cache/asmjs/libcxx_noexcept.a" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libcxxabi.bc... (this will be cached in "/private/tmp/nix-build-meguca-unstable-2018-07-01.drv-0/.emscripten_cache/asmjs/libcxxabi.bc" for subsequent builds)
/nix/store/zkbx6mlnkr640sg2x9fpnnpzxf3dgs1d-emscripten-1.37.36/share/emscripten/system/lib/libcxxabi/src/cxa_aux_runtime.cpp:22:1: error: unknown type name 'LIBCXXABI_NORETURN'
LIBCXXABI_NORETURN
^
/nix/store/zkbx6mlnkr640sg2x9fpnnpzxf3dgs1d-emscripten-1.37.36/share/emscripten/system/lib/libcxxabi/src/cxa_aux_runtime.cpp:23:1: error: expected unqualified-id
void __cxa_bad_cast (void) {
^
/nix/store/zkbx6mlnkr640sg2x9fpnnpzxf3dgs1d-emscripten-1.37.36/share/emscripten/system/lib/libcxxabi/src/cxa_aux_runtime.cpp:27:1: error: unknown type name 'LIBCXXABI_NORETURN'
LIBCXXABI_NORETURN
^
/nix/store/zkbx6mlnkr640sg2x9fpnnpzxf3dgs1d-emscripten-1.37.36/share/emscripten/system/lib/libcxxabi/src/cxa_aux_runtime.cpp:28:1: error: expected unqualified-id
void __cxa_bad_typeid(void) {
^
4 errors generated.
```

**Comment by bakape** [comment]
Nope. Don't own a mac and Hackintosh is dum. This seems to be a problem
with emscripten on NIX/Darwin either way.

On 2 Jul 2018 1:53 pm, "チルノ" <notifications@github.com> wrote:

Having a problem here <https://github.com/NixOS/nixpkgs/pull/41823>.
Have you tested any emscripten stuff on a Mac? Think it might be a
Nix-specific issue?
It seems to not want to build libcxxabi.

make[2]: Leaving directory
'/private/tmp/nix-build-meguca-unstable-2018-07-01.drv-0/go/src/github.com/bakape/meguca/client_cpp/src'
emcc src/*.bc src/page/*.bc src/posts/*.bc src/options/*.bc
src/connection/*.bc brunhild/*.bc -o linked.bc -std=c++1z --bind -O3
-g0 -I/private/tmp/nix-build-meguca-unstable-2018-07-01.drv-0/go/src/github.com/bakape/meguca/client_cpp/json/include
--llvm-lto 3 -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY=67108864 -s
ALLOW_MEMORY_GROWTH=1 -Wno-almost-asm -s NO_FILESYSTEM=1
emcc linked.bc -o main.js --separate-asm -Wno-separate-asm -std=c++1z
--bind -O3 -g0 -I/private/tmp/nix-build-meguca-unstable-2018-07-01.drv-0/go/src/github.com/bakape/meguca/client_cpp/json/include
--llvm-lto 3 -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY=67108864 -s
ALLOW_MEMORY_GROWTH=1 -Wno-almost-asm -s NO_FILESYSTEM=1
INFO:root:generating system library: libcxx_noexcept.a... (this will
be cached in "/private/tmp/nix-build-meguca-unstable-2018-07-01.drv-0/.emscripten_cache/asmjs/libcxx_noexcept.a"
for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libcxxabi.bc... (this will be
cached in "/private/tmp/nix-build-meguca-unstable-2018-07-01.drv-0/.emscripten_cache/asmjs/libcxxabi.bc"
for subsequent builds)
/nix/store/zkbx6mlnkr640sg2x9fpnnpzxf3dgs1d-emscripten-1.37.36/share/emscripten/system/lib/libcxxabi/src/cxa_aux_runtime.cpp:22:1:
error: unknown type name 'LIBCXXABI_NORETURN'
LIBCXXABI_NORETURN
^
/nix/store/zkbx6mlnkr640sg2x9fpnnpzxf3dgs1d-emscripten-1.37.36/share/emscripten/system/lib/libcxxabi/src/cxa_aux_runtime.cpp:23:1:
error: expected unqualified-id
void __cxa_bad_cast (void) {
^
/nix/store/zkbx6mlnkr640sg2x9fpnnpzxf3dgs1d-emscripten-1.37.36/share/emscripten/system/lib/libcxxabi/src/cxa_aux_runtime.cpp:27:1:
error: unknown type name 'LIBCXXABI_NORETURN'
LIBCXXABI_NORETURN
^
/nix/store/zkbx6mlnkr640sg2x9fpnnpzxf3dgs1d-emscripten-1.37.36/share/emscripten/system/lib/libcxxabi/src/cxa_aux_runtime.cpp:28:1:
error: expected unqualified-id
void __cxa_bad_typeid(void) {
^
4 errors generated.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bakape/meguca/issues/767>, or mute the thread

**Comment by Chiiruno** [comment]
I'll investigate a bit more.
I guess I'll keep this open until I know whether it's a configuration problem on this repo's part or not.
